Repository 9weeks-app-web/Team-4, pull requests merged in 2024-01, with the labels that each got.

#7 Feature/포트폴리오 페이지 전체 레이아웃 잡기
  next.config.js
  package.json
  src/app/Provider.tsx
  src/app/api/portfolios/(dummys)/index.ts
  src/app/api/portfolios/count/route.ts
  src/app/api/portfolios/route.ts
  src/app/layout.tsx
  src/app/portfolio/(components)/(Banner)/index.tsx
  src/app/portfolio/(components)/(List)/Category.tsx
  src/app/portfolio/(components)/(List)/Contents.tsx
  src/app/portfolio/(components)/(List)/index.tsx
  src/app/portfolio/(constants)/index.ts
  src/app/portfolio/(types)/index.d.ts
  src/app/portfolio/layout.tsx
  src/app/portfolio/page.tsx
  src/types/portfolio.ts
  src/utils/api.ts
  yarn.lock
Labels: Pull Request, Feature

#8 PR: 모임 퍼블리싱
  package.json
  src/app/gathering/(components)/button/ButtonBasic.tsx
  src/app/gathering/(components)/button/ButtonRound.tsx
  src/app/gathering/(components)/card/LargeGatheringCard.tsx
  src/app/gathering/(components)/card/NormalGatheringCard.tsx
  src/app/gathering/(components)/card/RetrospectCard.tsx
  src/app/gathering/(components)/input/ComboBox.tsx
  src/app/gathering/(components)/input/Counter.tsx
  src/app/gathering/(components)/input/Input.tsx
  src/app/gathering/(components)/input/Radio.tsx
  src/app/gathering/(components)/input/Textarea.tsx
  src/app/gathering/(components)/section/create/ImageSection.tsx
  src/app/gathering/(components)/section/create/MultipleSection.tsx
  src/app/gathering/(components)/section/create/SingleSection.tsx
  src/app/gathering/(components)/section/main/AdvertisementSection.tsx
  src/app/gathering/(components)/section/main/DeadlineGatheringSection.tsx
  src/app/gathering/(components)/section/main/GatheringBannerSection.tsx
  src/app/gathering/(components)/section/main/GatheringGuideSection.tsx
  src/app/gathering/(components)/section/main/MainGatheringSection.tsx
  src/app/gathering/(components)/section/main/RecommendGatheringSection.tsx
  src/app/gathering/(components)/section/main/RetrospectSection.tsx
  src/app/gathering/(components)/section/post/Comment.tsx
  src/app/gathering/(components)/section/post/GatheringDetailHeader.tsx
  src/app/gathering/(components)/section/post/GatheringInfoSection.tsx
  src/app/gathering/(components)/section/post/RecommendGathering.tsx
  src/app/gathering/(components)/section/post/Section.tsx
  src/app/gathering/(components)/section/post/TeamInfo.tsx
  src/app/gathering/layout.tsx
  src/app/gathering/page.tsx
  src/app/gathering/project/[postId]/page.tsx
  src/app/gathering/project/new/page.tsx
  src/app/gathering/retrospect/(components)/RetrospectBannerSection.tsx
  src/app/gathering/retrospect/(components)/RetrospectGridSection.tsx
  src/app/gathering/retrospect/[postId]/page.tsx
  src/app/gathering/retrospect/new/page.tsx
  src/app/gathering/retrospect/page.tsx
  src/app/gathering/study/[postId]/page.tsx
  src/app/gathering/study/new/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  yarn.lock
Labels: Pull Request

#10 Feat: 커뮤니티 퍼블리싱 1차
  package.json
  public/images/bookmark.png
  public/images/chat.png
  public/images/earth.png
  public/images/eye.png
  public/images/like.png
  public/images/star.png
  src/app/community/(components)/AllBoradCard.tsx
  src/app/community/(components)/Card.tsx
  src/app/community/(components)/Chat.tsx
  src/app/community/(components)/FreeCard.tsx
  src/app/community/(components)/HotBorad.tsx
  src/app/community/(components)/MarkDown.tsx
  src/app/community/(components)/MarkDownEditor.tsx
  src/app/community/(components)/PollCard.tsx
  src/app/community/(components)/SideBar.tsx
  src/app/community/(components)/SideWrite.tsx
  src/app/community/(components)/SurveyCard.tsx
  src/app/community/[category]/[id]/page.tsx
  src/app/community/[category]/page.tsx
  src/app/community/api/community/(dummys)/index.tsx
  src/app/community/jobchat/page.tsx
  src/app/community/layout.tsx
  src/app/community/page.tsx
  src/app/community/post/(components)/SurveyPostCard.tsx
  src/app/community/post/page.tsx
  src/app/community/survey/page.tsx
  yarn.lock
Labels: Feature

#12 PR: 모임 메인 api 작업
  package.json
  public/images/gathering/SFAC.svg
  public/images/gathering/bell.svg
  public/images/gathering/bookmark.svg
  public/images/gathering/chat_bubble.svg
  public/images/gathering/close_quote.svg
  public/images/gathering/double_left_arrow.svg
  public/images/gathering/double_right_arrow.svg
  public/images/gathering/left_arrow.svg
  public/images/gathering/like.svg
  public/images/gathering/main_banner.png
  public/images/gathering/open_quote.svg
  public/images/gathering/person.svg
  public/images/gathering/right_arrow.svg
  public/images/gathering/right_arrow2.svg
  public/images/gathering/search.svg
  public/images/gathering/speech_bubble.svg
  public/images/gathering/view.svg
  src/app/api/gathering/(dummy)/index.ts
  src/app/api/gathering/(dummy)/project/index.ts
  src/app/api/gathering/(dummy)/retrospect/index.ts
  src/app/api/gathering/(dummy)/study/index.ts
  src/app/api/gathering/deadline/route.ts
  src/app/api/gathering/recommend/route.ts
  src/app/api/gathering/retrospect/[postId]/route.ts
  src/app/api/gathering/retrospect/route.ts
  src/app/api/gathering/route.ts
  src/app/gathering/(components)/button/ButtonBasic.tsx
  src/app/gathering/(components)/button/ButtonSimple.tsx
  src/app/gathering/(components)/card/LargeGatheringCard.tsx
  src/app/gathering/(components)/card/LargeRetrospectCard.tsx
  src/app/gathering/(components)/card/NormalGatheringCard.tsx
  src/app/gathering/(components)/card/RetrospectCard.tsx
  src/app/gathering/(components)/chip/ChipBasic.tsx
  src/app/gathering/(components)/chip/ChipPrimary.tsx
  src/app/gathering/(components)/chip/ChipSmall.tsx
  src/app/gathering/(components)/input/ComboBox.tsx
  src/app/gathering/(components)/section/main/AdvertisementSection.tsx
  src/app/gathering/(components)/section/main/DeadlineGatheringSection.tsx
  src/app/gathering/(components)/section/main/GatheringBannerSection.tsx
  src/app/gathering/(components)/section/main/GatheringGuideSection.tsx
  src/app/gathering/(components)/section/main/MainGatheringSection.tsx
  src/app/gathering/(components)/section/main/RecommendGatheringSection.tsx
  src/app/gathering/(components)/section/main/RetrospectSection.tsx
  src/app/gathering/page.tsx
  src/app/gathering/retrospect/(components)/RetrospectBannerSection.tsx
  src/app/gathering/retrospect/(components)/RetrospectGridSection.tsx
  src/types/gathering.ts
  yarn.lock
Labels: Pull Request

#13 Feature/포트폴리오 상세보기 모달 만들기
  public/portfolios/arrow_down.svg
  public/portfolios/banner.png
  public/portfolios/basic_profile.svg
  public/portfolios/bookmark.svg
  public/portfolios/chat.svg
  public/portfolios/clipboard.svg
  public/portfolios/comment.svg
  public/portfolios/comment_upload.svg
  public/portfolios/create_button_blue.svg
  public/portfolios/cross.svg
  public/portfolios/folder.svg
  public/portfolios/hire.svg
  public/portfolios/hit.svg
  public/portfolios/like.svg
  public/portfolios/modal_like.svg
  public/portfolios/paper.svg
  public/portfolios/reply.svg
  public/portfolios/screenshot.png
  public/portfolios/share.svg
  public/portfolios/star.svg
  public/portfolios/thumbs_up.svg
  public/portfolios/upload_blue.svg
  src/app/api/portfolios/(dummys)/index.ts
  src/app/api/portfolios/detail/route.ts
  src/app/api/portfolios/route.ts
  src/app/api/portfolios/users/route.ts
  src/app/portfolio/(components)/(List)/Contents.tsx
  src/app/portfolio/(components)/(List)/index.tsx
  src/app/portfolio/(components)/(Modal)/index.tsx
  src/app/portfolio/(components)/(detail)/(ModalRightContent)/(Collection)/Collection.tsx
  src/app/portfolio/(components)/(detail)/(ModalRightContent)/(Comment)/Container.tsx
  src/app/portfolio/(components)/(detail)/(ModalRightContent)/(Comment)/Content.tsx
  src/app/portfolio/(components)/(detail)/(ModalRightContent)/(Comment)/Input.tsx
  src/app/portfolio/(components)/(detail)/(ModalRightContent)/(Comment)/Re.tsx
  src/app/portfolio/(components)/(detail)/(ModalRightContent)/index.tsx
  src/app/portfolio/(components)/(detail)/UserOtherPortfolios.tsx
  src/app/portfolio/(components)/(detail)/index.tsx
  src/app/portfolio/layout.tsx
  src/app/portfolio/upload/(components)/(CenterContent)/index.tsx
  src/app/portfolio/upload/(components)/(leftSideContent)/index.tsx
  src/app/portfolio/upload/(components)/(rightSideContent)/index.tsx
  src/app/portfolio/upload/(components)/index.tsx
  src/app/portfolio/upload/layout.tsx
  src/app/portfolio/upload/page.tsx
  src/types/portfolio.ts
  src/utils/dateFormat.ts
  tsconfig.json
Labels: Feature

#14 PR: 모임 메인 페이지 작업
  package.json
  public/images/gathering/arrow_down.svg
  public/images/gathering/badge1.svg
  public/images/gathering/badge2.svg
  public/images/gathering/badge3.svg
  public/images/gathering/badge4.svg
  public/images/gathering/document.svg
  public/images/gathering/laurel.svg
  public/images/gathering/pencil.svg
  public/images/gathering/plus.svg
  public/images/gathering/rank.svg
  public/images/gathering/spectrum.svg
  public/images/gathering/sticky_banner.svg
  public/images/gathering/x.svg
  src/app/api/gathering/(dummy)/index.ts
  src/app/api/gathering/(dummy)/project/index.ts
  src/app/api/gathering/(dummy)/respecter/index.ts
  src/app/api/gathering/(dummy)/retrospect/index.ts
  src/app/api/gathering/recommend/route.ts
  src/app/api/gathering/respecter/route.ts
  src/app/api/gathering/respecter/today/route.ts
  src/app/api/gathering/retrospect/route.ts
  src/app/api/gathering/route.ts
  src/app/gathering/(components)/button/ButtonBasic.tsx
  src/app/gathering/(components)/button/ButtonRound.tsx
  src/app/gathering/(components)/button/ButtonSimple.tsx
  src/app/gathering/(components)/card/LargeGatheringCard.tsx
  src/app/gathering/(components)/card/LargeRetrospectCard.tsx
  src/app/gathering/(components)/card/NormalGatheringCard.tsx
  src/app/gathering/(components)/card/RankerCard.tsx
  src/app/gathering/(components)/card/RespecterCard.tsx
  src/app/gathering/(components)/card/SmallRespecterCard.tsx
  src/app/gathering/(components)/card/ThumbnailGatheringCard.tsx
  src/app/gathering/(components)/chip/ChipSmall.tsx
  src/app/gathering/(components)/input/ComboBox.tsx
  src/app/gathering/(components)/section/create/ChartSection.tsx
  src/app/gathering/(components)/section/main/AdvertisementSection.tsx
  src/app/gathering/(components)/section/main/DeadlineGatheringSection.tsx
  src/app/gathering/(components)/section/main/FloatingSection.tsx
  src/app/gathering/(components)/section/main/GatheringBannerSection.tsx
  src/app/gathering/(components)/section/main/GatheringGuideSection.tsx
  src/app/gathering/(components)/section/main/MainGatheringSection.tsx
  src/app/gathering/(components)/section/main/RecommendGatheringSection.tsx
  src/app/gathering/(components)/section/main/RespectRankSection.tsx
  src/app/gathering/(components)/section/main/RetrospectSection.tsx
  src/app/gathering/(components)/section/main/TodayRespecterSection.tsx
  src/app/gathering/(components)/section/post/GatheringDetailHeader.tsx
  src/app/gathering/page.tsx
  src/app/gathering/project/new/page.tsx
  src/app/gathering/retrospect/(components)/RetrospectBannerSection.tsx
  src/app/gathering/retrospect/(components)/RetrospectGridSection.tsx
  src/app/gathering/retrospect/page.tsx
  src/app/globals.css
  src/components/chart/Radar.tsx
  src/types/gathering.ts
  src/types/portfolio.ts
  tailwind.config.ts
  yarn.lock
Labels: Pull Request

#16 Feature/포트폴리오 글 작성 페이지 생성
  public/portfolios/1.png
  public/portfolios/2.png
  public/portfolios/3.png
  public/portfolios/4.png
  public/portfolios/Movie.svg
  public/portfolios/Text.svg
  public/portfolios/embed.svg
  public/portfolios/image.svg
  public/portfolios/left_arrow.svg
  public/portfolios/preview.svg
  src/app/globals.css
  src/app/layout.tsx
  src/app/portfolio/(components)/(detail)/(ModalRightContent)/(Collection)/Collection.tsx
  src/app/portfolio/layout.tsx
  src/app/portfolio/upload/(components)/(CenterContent)/index.tsx
  src/app/portfolio/upload/(components)/(leftSideContent)/index.tsx
  src/app/portfolio/upload/(components)/(rightSideContent)/index.tsx
  src/app/portfolio/upload/(components)/index.tsx
  src/app/portfolio/upload/layout.tsx
  tailwind.config.ts
Labels: Feature

#17 Feature/커뮤니티 상세게시글
  public/images/community/Vector.png
  public/images/community/badge.png
  public/images/community/bookmark.png
  public/images/community/bookmark_hover.png
  public/images/community/btn.png
  public/images/community/btn_hover.png
  public/images/community/chat.png
  public/images/community/chat_hover.png
  public/images/community/comment.png
  public/images/community/commentLike.png
  public/images/community/commentLike_hover.png
  public/images/community/comment_hover.png
  public/images/community/cry.png
  public/images/community/earth.png
  public/images/community/eye.png
  public/images/community/eye_hover.png
  public/images/community/fire.png
  public/images/community/hand.png
  public/images/community/heart.png
  public/images/community/like.png
  public/images/community/like_hover.png
  public/images/community/plus.png
  public/images/community/right.png
  public/images/community/star.png
  public/images/community/thumb.png
  src/app/community/(components)/AllBoradCard.tsx
  src/app/community/(components)/Card.tsx
  src/app/community/(components)/CategoryCard.tsx
  src/app/community/(components)/Comment.tsx
  src/app/community/(components)/FindCategory.tsx
  src/app/community/(components)/FreeCard.tsx
  src/app/community/(components)/HotBorad.tsx
  src/app/community/(components)/MarkDown.tsx
  src/app/community/(components)/PollCard.tsx
  src/app/community/(components)/SideBar.tsx
  src/app/community/(components)/SubComment.tsx
  src/app/community/(components)/SurveyCard.tsx
  src/app/community/(components)/emojiModal/EmojiModal.tsx
  src/app/community/(components)/imageComponents/Badge.tsx
  src/app/community/(components)/imageComponents/Bookmark.tsx
  src/app/community/(components)/imageComponents/Chat.tsx
  src/app/community/(components)/imageComponents/Comment.tsx
  src/app/community/(components)/imageComponents/CommentLike.tsx
  src/app/community/(components)/imageComponents/Emoji.tsx
  src/app/community/(components)/imageComponents/Eye.tsx
  src/app/community/(components)/imageComponents/Like.tsx
  src/app/community/(components)/imageComponents/Profile.tsx
  src/app/community/(components)/imageComponents/Right.tsx
  src/app/community/[category]/[id]/page.tsx
  src/app/community/[category]/page.tsx
  src/app/community/api/community/(dummys)/comment.tsx
  src/app/community/api/community/(dummys)/index.tsx
  src/app/community/api/community/route.tsx
  src/app/community/layout.tsx
  src/app/community/page.tsx
  src/app/community/post/page.tsx
  src/app/community/survey/page.tsx
  src/types/community.ts
  tailwind.config.ts
Labels: Feature

#19 PR: 모임 생성 페이지 기능 및 디자인 작업
  package.json
  public/images/gathering/banner.svg
  public/images/gathering/blue_plus.svg
  public/images/gathering/main_banner.png
  public/images/gathering/profile.svg
  public/images/gathering/star.svg
  public/images/gathering/team_profile.svg
  src/app/community/(components)/MarkDownEditor.tsx
  src/app/gathering/(components)/button/ButtonBasic.tsx
  src/app/gathering/(components)/button/ButtonRound.tsx
  src/app/gathering/(components)/chip/ChipPrimary.tsx
  src/app/gathering/(components)/input/ComboBox.tsx
  src/app/gathering/(components)/input/Counter.tsx
  src/app/gathering/(components)/input/Input.tsx
  src/app/gathering/(components)/input/Radio.tsx
  src/app/gathering/(components)/input/Textarea.tsx
  src/app/gathering/(components)/section/create/ChartSection.tsx
  src/app/gathering/(components)/section/create/ImageSection.tsx
  src/app/gathering/(components)/section/create/MultipleSection.tsx
  src/app/gathering/(components)/section/create/SingleSection.tsx
  src/app/gathering/(components)/section/main/FloatingSection.tsx
  src/app/gathering/(components)/section/main/GatheringBannerSection.tsx
  src/app/gathering/(components)/section/main/RetrospectSection.tsx
  src/app/gathering/project/new/page.tsx
  src/app/gathering/retrospect/(components)/RetrospectGridSection.tsx
  src/app/gathering/retrospect/new/page.tsx
  src/app/gathering/study/new/page.tsx
  src/app/globals.css
  tailwind.config.ts
  yarn.lock
Labels: Pull Request

#20 PR: 모임 게시글 페이지 작업
  public/images/gathering/arrow_button.svg
  public/images/gathering/arrow_in.svg
  public/images/gathering/avengers.svg
  public/images/gathering/bookmark_0.svg
  public/images/gathering/bookmark_0_fill.svg
  public/images/gathering/bookmark_40.svg
  public/images/gathering/bookmark_fill.svg
  public/images/gathering/chat_bubble_40.svg
  public/images/gathering/figma.svg
  public/images/gathering/heart.svg
  public/images/gathering/java.svg
  public/images/gathering/left_arrow2.svg
  public/images/gathering/like.svg
  public/images/gathering/react.svg
  public/images/gathering/retrospect1.svg
  public/images/gathering/retrospect_banner.svg
  public/images/gathering/share.svg
  public/images/gathering/spectrum2.svg
  public/images/gathering/spectrum3.svg
  public/images/gathering/spectrum4.svg
  public/images/gathering/view_40.svg
  src/app/api/gathering/(dummy)/retrospect/index.ts
  src/app/api/gathering/retrospect/route.ts
  src/app/gathering/(components)/button/ButtonBasic.tsx
  src/app/gathering/(components)/button/ButtonRound.tsx
  src/app/gathering/(components)/button/ButtonSmall.tsx
  src/app/gathering/(components)/card/NormalGatheringCard.tsx
  src/app/gathering/(components)/card/ThumbnailGatheringCard.tsx
  src/app/gathering/(components)/chip/ChipRound.tsx
  src/app/gathering/(components)/input/Input.tsx
  src/app/gathering/(components)/section/main/RetrospectSection.tsx
  src/app/gathering/(components)/section/post/Comment.tsx
  src/app/gathering/(components)/section/post/CommentSection.tsx
  src/app/gathering/(components)/section/post/GatheringDetailHeader.tsx
  src/app/gathering/(components)/section/post/GatheringInfoSection.tsx
  src/app/gathering/(components)/section/post/RecommendGathering.tsx
  src/app/gathering/(components)/section/post/Section.tsx
  src/app/gathering/(components)/section/post/TeamInfo.tsx
  src/app/gathering/project/[postId]/page.tsx
  src/app/gathering/retrospect/[postId]/page.tsx
  src/app/gathering/study/[postId]/page.tsx
  src/app/globals.css
  src/components/chart/Radar.tsx
  src/types/gathering.ts
Labels: Pull Request

#23 Feature/커뮤니티 상세게시글
  public/images/community/Ellipse_1.png
  public/images/community/Ellipse_2.png
  public/images/community/Ellipse_3.png
  public/images/community/Ellipse_4.png
  public/images/community/Ellipse_5.png
  public/images/community/Ellipse_6.png
  public/images/community/badge.png
  public/images/community/badge1.png
  public/images/community/badge2.png
  public/images/community/badge3.png
  public/images/community/badge4.png
  public/images/community/badge5.png
  public/images/community/facebook.png
  public/images/community/kakao.png
  public/images/community/link.png
  public/images/community/people.png
  public/images/community/thumnails/ux_1.jpg
  public/images/community/thumnails/ux_10.jpg
  public/images/community/thumnails/ux_11.jpg
  public/images/community/thumnails/ux_2.jpg
  public/images/community/thumnails/ux_3.jpg
  public/images/community/thumnails/ux_4.jpg
  public/images/community/thumnails/ux_5.png
  public/images/community/thumnails/ux_6.jpg
  public/images/community/thumnails/ux_7.jpg
  public/images/community/thumnails/ux_8.jpg
  public/images/community/thumnails/ux_9.jpg
  public/images/community/x_fill.png
  src/app/community/(components)/AllBoradCard.tsx
  src/app/community/(components)/Card.tsx
  src/app/community/(components)/CategoryCard.tsx
  src/app/community/(components)/ChatCard.tsx
  src/app/community/(components)/Comment.tsx
  src/app/community/(components)/MarkDownEditor.tsx
  src/app/community/(components)/SubComment.tsx
  src/app/community/(components)/SurveyCard.tsx
  src/app/community/(components)/TimeCal.tsx
  src/app/community/(components)/imageComponents/shareIcons.tsx
  src/app/community/[category]/[id]/page.tsx
  src/app/community/api/community/(dummys)/chat.tsx
  src/app/community/api/community/(dummys)/comment.tsx
  src/app/community/api/community/(dummys)/index.tsx
  src/app/community/chatroom/(components)/ChatRoomCard.tsx
  src/app/community/chatroom/(components)/ChatRoomChatCard.tsx
  src/app/community/chatroom/(components)/SelectedChatCard.tsx
  src/app/community/chatroom/(components)/SelectedChatRoomCard.tsx
  src/app/community/chatroom/page.tsx
  src/app/community/jobchat/page.tsx
  src/app/community/page.tsx
  src/app/community/post/(components)/SurveyPostCard.tsx
  src/app/community/post/page.tsx
  src/app/community/style.css
  src/app/community/types/chat.tsx
Labels: Feature
